### ISSUE TITLE
Loading Files with REST

### ISSUE THREAD

**Issue by ArcosBinary** [advantageous/qbit#395]
Hi,

I've got one more question. :)
What's the correct way to load a File via REST interface?
That's my approach:

The code for the sevice which offers the File
```Java
@RequestMapping(value = "/loadFile", method = RequestMethod.GET)
	public String getFile(){
		return JsonFactory.toJson(clientLoader.getFile());
}
```
and the client code which want's to get the File
```Java
	HttpResponse jsonFile = httpClient.get("/services/task-service/loadFile");

	return JsonFactory.fromJson(jsonFile.body(), File.class);
```
But if I use this code, I get an error:
````
Caused by: java.lang.ClassCastException: io.advantageous.boon.core.value.CharSequenceValue cannot be cast to java.io.File
````
Well, I don't get it. How to use it correctly?

edit: When I call the interface with my browser, I only get the Path:

````
"\"D:\\PieChart.jar\""
````

When returning the File without using the JsonFactory:
````
"D:\PieChart.jar"
````

**Comment by RichardHightower** [comment]
I am doing this from memory so forgive me if I miss a few things.

#### One way
```java
@RequestMapping(value = "/loadFile", method = RequestMethod.GET)
    public Map<String, Object> getFile(){
         return JsonFactory.fromJson(JsonFactory.toJson(clientLoader.getFile()));
}
```
Basically turn it into a map, then sent it out the normal route.

Another way if that does not work...

Use `BoonJsonMapper` this is the default JSON parser / serializer for QBit.

This way I am 90% sure it will work.

##Option 2
```java
import io.advantageous.qbit.Factory;

//constructor
final Factory factory = QBit.factory();
JsonMapper mapper = factory.createJsonMapper();

@RequestMapping(value = "/loadFile", method = RequestMethod.GET)
    public Map<String, Object> getFile(){
        //
    <K,V> Map<K, V> fromJsonMap(String json, Class<K> componentClassKey, Class<V> componentClassValue);
         return mapper.fromJsonMap(clientLoader.getFile(), String.class, Object.class);
}

```

This way I am 99% sure will work. 

Now let's say you want to get clever and you don't want to parse and then turn around a deserialize a JSON string. 


##Option 3
```java
@RequestMapping(value = "/loadFile", method = RequestMethod.GET)
    public void getFile(final Callback<HttpResponse> respnoseCallback){
         HttpResponseBuilder httpResponseBuilder = HttpResponseBuilder.httpResponseBuilder();
         httpResponseBuilder.setBody(clientLoader.getFile());
         httpResponseBuilder.setCode(200);
         httpResponseBuilder.setContentType("application/json");
         respnoseCallback.returnThis(httpResponseBuilder.build());
}
```

(Remember I am doing this from memory so spelling and names could be off but that should give you enough of a hint.)



Option 3 IMO is the best. 

Check out for actual spelling
https://github.com/advantageous/qbit/blob/master/qbit/core/src/main/java/io/advantageous/qbit/http/request/HttpResponseBuilder.java

https://github.com/advantageous/qbit/blob/master/qbit/core/src/main/java/io/advantageous/qbit/reactive/Callback.java


If you download the source and search for usages of `HttpTextResponse`, `HttpBinaryResponse` and `HttpResponse`, you can see where we handle it specially so that you can do whatever you want. 

Now how can you pay it forward. 

You can fork the project and add some document.
You can write up a little tutorial on using final Callback<HttpResponse> in markdown and post it on your blog and send us a copy to put into our wiki. :)

contact me at richard  hightower at gmail dot com so we can connect and I can learn about how you are using QBit.

**Comment by RichardHightower** [comment]
Hey on that last option. You need to add a bogus header. 
There is a patch but it will be in the new release. See PR #399.
